name: Build and Test Docker Compose Services

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  build-test-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [kb, data-processing, api, rag, gui-panel, kpi-engine]  # Replace with your actual service names

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env file from secret
        run: echo "${{ secrets.RAG_ENV }}" >> rag/.env

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:latest
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Wait for services to initialize
        run: sleep 60

      - name: Test running services
        run: |
          SERVICES=$(docker-compose config --services)
          for SERVICE in $SERVICES; do
            CONTAINER_ID=$(docker ps -qf "name=${SERVICE}")
            STATUS=$(docker inspect -f '{{.State.Status}}' $CONTAINER_ID)
            if [ "$STATUS" != "running" ]; then
              echo "Service $SERVICE failed to run!"
              docker logs $CONTAINER_ID
              docker-compose down
              exit 1
            else
              echo "Service $SERVICE is running successfully."
            fi
          done

      - name: Stop and remove services
        run: docker-compose down
