name: Build and Test Docker Compose Services

on:
  pull_request:

jobs:
  build-and-test-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [database, kb, data-processing, api, rag, gui-panel, kpi-engine]  # Lista completa dei servizi.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secret
        run: echo "${{ secrets.RAG_ENV }}" > rag/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/smartfactory/${{ matrix.service }}:pr-${{ github.event.number }}
          push: false 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Run container for testing
        run: |
          docker run --rm --name test-${{ matrix.service }} -d ghcr.io/${{ github.repository_owner }}/smartfactory/${{ matrix.service }}:pr-${{ github.event.number }}
          sleep 60  # Attendi 60 secondi per verificarne la stabilità.
          docker stop test-${{ matrix.service }}
